import type { ProviderConfig, ProviderModelConfig } from "@mariozechner/pi-coding-agent";
import type { IntegrationProviderPayloadRewrite } from "./request_rewrite.ts";

type WarnFn = (message: string) => void;

export type IntegrationProviderInfo = {
  config: ProviderConfig;
  // Exact model aliases generated by this extension to preserve duplicate names.
  modelAliases?: ReadonlyMap<string, string>;
  // Exact generated model ids that need ChatGPT /codex/responses payload shaping.
  chatGPTModelIds?: ReadonlySet<string>;
  // Base URLs this extension registered for the integration provider.
  baseUrls: ReadonlySet<string>;
};

export interface CatalogCompat {
  supportsDeveloperRole?: boolean;
  maxTokensField?: string;
  supportsReasoningEffort?: boolean;
  thinkingFormat?: string;
  cacheControlFormat?: string;
}

export interface CatalogModel {
  id: string;
  name?: string;
  type?: string;
  reasoning?: boolean;
  input?: ("text" | "image")[];
  contextWindow?: number;
  maxTokens?: number;
  cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
  compat?: CatalogCompat;
}

export interface CatalogProvider {
  id: string;
  path: string;
  api?: string;
  models: CatalogModel[];
}

export interface Catalog {
  schemaVersion: number;
  providers: CatalogProvider[];
}

interface ReflectionIntegration {
  name?: string;
  type?: string;
  team?: boolean;
  help?: string;
}

interface ReflectionIntegrationsResponse {
  integrations?: ReflectionIntegration[];
}

interface IntegrationModelArchitecture {
  input_modalities?: string[];
  output_modalities?: string[];
}

interface IntegrationModelLimits {
  context_window?: number;
  max_output_tokens?: number;
}

interface IntegrationModelExeDev {
  mode?: string;
}

interface IntegrationModel {
  id: string;
  name?: string;
  provider: string;
  native_id?: string;
  apis?: string[];
  architecture?: IntegrationModelArchitecture;
  limits?: IntegrationModelLimits;
  exe_dev?: IntegrationModelExeDev;
}

interface IntegrationCatalog {
  schema_version: number;
  models: IntegrationModel[];
}

export type DiscoveredIntegration = {
  name: string;
  baseURL: string;
  catalog?: IntegrationCatalog;
};

type CompatBag = {
  supportsDeveloperRole?: boolean;
  supportsReasoningEffort?: boolean;
  maxTokensField?: "max_tokens" | "max_completion_tokens";
  thinkingFormat?: "openai" | "openrouter" | "deepseek" | "zai" | "qwen" | "qwen-chat-template";
  cacheControlFormat?: "anthropic";
};

export type JSONFetcher = (url: string) => Promise<unknown | undefined>;

// Both the integration catalog and the bundled pricing sidecar currently use
// schema version 1. Unknown shapes are ignored rather than becoming routes.
export const SCHEMA_VERSION = 1;

const KNOWN_THINKING_FORMATS: ReadonlySet<string> = new Set([
  "openai",
  "openrouter",
  "deepseek",
  "zai",
  "qwen",
  "qwen-chat-template",
]);
const KNOWN_MAX_TOKENS_FIELDS: ReadonlySet<string> = new Set(["max_tokens", "max_completion_tokens"]);
const KNOWN_CACHE_CONTROL_FORMATS: ReadonlySet<string> = new Set(["anthropic"]);

export function validCatalog(cat: unknown): cat is Catalog {
  if (!cat || typeof cat !== "object") return false;
  const c = cat as Catalog;
  if (c.schemaVersion !== SCHEMA_VERSION) return false;
  if (!Array.isArray(c.providers) || c.providers.length === 0) return false;
  return true;
}

function validIntegrationCatalog(cat: unknown): cat is IntegrationCatalog {
  if (!cat || typeof cat !== "object") return false;
  const c = cat as IntegrationCatalog;
  if (c.schema_version !== SCHEMA_VERSION) return false;
  if (!Array.isArray(c.models)) return false;
  return true;
}

export async function fetchJSONWithTimeout(url: string, timeoutMS: number): Promise<unknown | undefined> {
  const res = await fetch(url, { signal: AbortSignal.timeout(timeoutMS) });
  if (!res.ok) return undefined;
  return (await res.json()) as unknown;
}

function reflectionLLMIntegrations(reflection: unknown): ReflectionIntegration[] | undefined {
  const integrations = (reflection as ReflectionIntegrationsResponse | undefined)?.integrations;
  if (!Array.isArray(integrations)) return undefined;
  return integrations.filter(
    (integration) => integration.type === "llm" && typeof integration.name === "string" && integration.name.length > 0,
  );
}

async function fetchReflectionIntegrations(
  url: string,
  fetchJSON: JSONFetcher,
  warn: WarnFn,
): Promise<ReflectionIntegration[]> {
  let integrations: ReflectionIntegration[] | undefined;
  try {
    const reflection = await fetchJSON(url);
    integrations = reflectionLLMIntegrations(reflection);
    if (!integrations) throw new Error(`${url} returned unrecognized reflection shape`);
  } catch (err) {
    warn(`[pi-exe-dev] LLM integration reflection fetch failed: ${(err as Error).message}`);
    return [];
  }
  return integrations;
}

function defaultIntegrationBaseURL(integration: ReflectionIntegration): string {
  const name = integration.name as string;
  return integration.team === true ? `https://${name}.team.exe.xyz` : `https://${name}.int.exe.xyz`;
}

function integrationBaseURLCandidates(integration: ReflectionIntegration): string[] {
  const candidates: string[] = [];
  const add = (baseURL: string) => {
    if (!candidates.includes(baseURL)) candidates.push(baseURL);
  };

  for (const match of integration.help?.matchAll(/https?:\/\/[^\s'"`]+/g) ?? []) {
    try {
      const url = new URL(match[0]);
      if (
        url.hostname.endsWith(".int.exe.xyz") ||
        url.hostname.endsWith(".team.exe.xyz")
      ) {
        add(url.origin);
      }
    } catch {
      // Ignore prose that looked like a URL but was not parseable.
    }
  }

  if (integration.name) {
    if (integration.team === true) {
      add(`https://${integration.name}.team.exe.xyz`);
    } else {
      add(`https://${integration.name}.int.exe.xyz`);
    }
  }
  return candidates;
}

function firstAggregateErrorMessage(err: unknown): string {
  if (err instanceof AggregateError && err.errors.length > 0) {
    return (err.errors[0] as Error).message;
  }
  return (err as Error).message;
}

async function fetchIntegrationCatalog(
  integration: ReflectionIntegration,
  fetchJSON: JSONFetcher,
  warn: WarnFn,
): Promise<DiscoveredIntegration> {
  const name = integration.name as string;
  const candidates = integrationBaseURLCandidates(integration);
  if (candidates.length === 0) return { name, baseURL: defaultIntegrationBaseURL(integration) };

  try {
    return await Promise.any(
      candidates.map(async (baseURL) => {
        const catalog = await fetchJSON(`${baseURL}/models.json`);
        if (!validIntegrationCatalog(catalog)) {
          throw new Error(`${baseURL}/models.json returned unrecognized catalog shape`);
        }
        return { name, baseURL, catalog };
      }),
    );
  } catch (err) {
    warn(`[pi-exe-dev] LLM integration ${name} models.json fetch failed: ${firstAggregateErrorMessage(err)}`);
    return { name, baseURL: defaultIntegrationBaseURL(integration) };
  }
}

export async function discoverIntegrationCatalogs(
  reflectionURL: string,
  fetchJSON: JSONFetcher,
  warn: WarnFn = console.warn,
): Promise<{ found: boolean; integrations: DiscoveredIntegration[] }> {
  const llmIntegrations = await fetchReflectionIntegrations(reflectionURL, fetchJSON, warn);
  if (llmIntegrations.length === 0) return { found: false, integrations: [] };
  const integrations = await Promise.all(llmIntegrations.map((integration) => fetchIntegrationCatalog(integration, fetchJSON, warn)));
  return { found: true, integrations };
}

type IntegrationAPIAdapter = {
  catalogAPI: string;
  piAPI: NonNullable<ProviderConfig["api"]>;
  basePathSuffix: "" | "/v1";
};

// Protocol priority is independent of provider identity. New providers and
// BYOP entries work automatically when their catalog models advertise a wire
// protocol Pi already supports.
const INTEGRATION_API_ADAPTERS: readonly IntegrationAPIAdapter[] = [
  { catalogAPI: "openai_responses", piAPI: "openai-responses", basePathSuffix: "/v1" },
  { catalogAPI: "anthropic_messages", piAPI: "anthropic-messages", basePathSuffix: "" },
  { catalogAPI: "openai_chat", piAPI: "openai-completions", basePathSuffix: "/v1" },
];

function integrationAPIAdapter(model: IntegrationModel): IntegrationAPIAdapter | undefined {
  const apis = new Set(model.apis ?? []);
  return INTEGRATION_API_ADAPTERS.find((adapter) => apis.has(adapter.catalogAPI));
}

function validIntegrationProviderID(provider: string): boolean {
  return provider !== "accounts" && /^[a-z0-9_-]+$/.test(provider);
}

function integrationProviderBaseURL(
  baseURL: string,
  provider: string,
  adapter: IntegrationAPIAdapter,
): string {
  return `${baseURL.replace(/\/+$/, "")}/${provider}${adapter.basePathSuffix}`;
}

function integrationModelID(model: IntegrationModel): string | undefined {
  const id = model.native_id || model.id;
  return typeof id === "string" && id.length > 0 ? id : undefined;
}

function integrationAliasModelID(modelID: string, integrationName: string): string {
  return `${modelID}@${integrationName}`;
}

function inputModalities(model: IntegrationModel, fallback: CatalogModel | undefined): ("text" | "image")[] {
  const out = (model.architecture?.input_modalities ?? []).filter(
    (input): input is "text" | "image" => input === "text" || input === "image",
  );
  if (out.length > 0) return out;
  if (fallback?.input?.length) return fallback.input;
  return ["text"];
}

function costCatalogIndex(catalog: Catalog | undefined): Map<string, CatalogModel> {
  const out = new Map<string, CatalogModel>();
  if (!catalog) return out;
  for (const provider of catalog.providers) {
    for (const model of provider.models) {
      out.set(`${provider.id}\0${model.id}`, model);
    }
  }
  return out;
}

function fallbackCatalogModel(
  costs: Map<string, CatalogModel>,
  provider: string,
  modelID: string,
  requestID: string,
): CatalogModel | undefined {
  return costs.get(`${provider}\0${modelID}`) ?? costs.get(`${provider}\0${requestID}`);
}

function configFromIntegrationModel(
  integration: DiscoveredIntegration,
  model: IntegrationModel,
  fallback: CatalogModel | undefined,
): ProviderModelConfig | undefined {
  if (!validIntegrationProviderID(model.provider)) return undefined;
  const adapter = integrationAPIAdapter(model);
  if (!adapter) return undefined;
  const baseUrl = integrationProviderBaseURL(integration.baseURL, model.provider, adapter);

  const modelID = integrationModelID(model);
  if (!modelID) return undefined;
  const compat = sanitizeCompat(fallback?.compat, model.provider, modelID);
  return {
    id: modelID,
    name: model.name || fallback?.name || modelID,
    api: adapter.piAPI,
    baseUrl,
    reasoning: fallback?.reasoning ?? false,
    input: inputModalities(model, fallback),
    contextWindow: model.limits?.context_window ?? fallback?.contextWindow ?? 128000,
    maxTokens: model.limits?.max_output_tokens ?? fallback?.maxTokens ?? 4096,
    cost: fallback?.cost ?? { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    ...(compat ? { compat: compat as ProviderModelConfig["compat"] } : {}),
  };
}

type IntegrationModelCandidate = {
  integration: DiscoveredIntegration;
  model: IntegrationModel;
  nativeID: string;
  config: ProviderModelConfig;
};

function integrationModelConfig(candidate: IntegrationModelCandidate): ProviderModelConfig {
  return {
    ...candidate.config,
    id: integrationAliasModelID(candidate.nativeID, candidate.integration.name),
    name: `${candidate.config.name} (${candidate.integration.name})`,
  };
}

function integrationModelNeedsChatGPTPayloadRewrite(candidate: IntegrationModelCandidate): boolean {
  return candidate.model.exe_dev?.mode === "chatgpt" && candidate.config.api === "openai-responses";
}

export function integrationProviderDisplayName(names: string[]): string {
  const uniq = Array.from(new Set(names)).sort();
  if (uniq.length === 0) return "llm";
  if (uniq.length <= 2) return uniq.join(", ");
  return `${uniq[0]} + ${uniq.length - 1} more`;
}

export function integrationPromptAvailabilityLabel(names: string[]): string {
  const uniq = Array.from(new Set(names)).sort();
  if (uniq.length <= 2) return uniq.join(", ");
  return `${uniq.slice(0, 2).join(", ")}, ...`;
}

export function providerInfosFromIntegrationCatalogs(
  integrations: DiscoveredIntegration[],
  pricingCatalog: Catalog | undefined,
  warn: WarnFn = console.warn,
): Map<string, IntegrationProviderInfo> {
  const costs = costCatalogIndex(pricingCatalog);
  const grouped = new Map<string, { names: string[]; candidates: IntegrationModelCandidate[] }>();
  const warnedMissingPricing = new Set<string>();

  for (const integration of integrations) {
    if (!integration.catalog) continue;
    for (const model of integration.catalog.models) {
      const provider = model.provider;
      const modelID = integrationModelID(model);
      if (!modelID) continue;
      const fallback = fallbackCatalogModel(costs, provider, modelID, model.id);
      const config = configFromIntegrationModel(integration, model, fallback);
      if (!config) continue;
      if (!fallback) warnedMissingPricing.add(`${provider}/${modelID}`);

      let entry = grouped.get(provider);
      if (!entry) {
        entry = { names: [], candidates: [] };
        grouped.set(provider, entry);
      }
      entry.names.push(integration.name);
      entry.candidates.push({ integration, model, nativeID: modelID, config });
    }
  }

  if (warnedMissingPricing.size === 1) {
    const [model] = warnedMissingPricing;
    warn(`[pi-exe-dev] missing pricing for integration model ${model}; pi usage cost will be reported as zero`);
  } else if (warnedMissingPricing.size > 1) {
    warn(
      `[pi-exe-dev] missing pricing for ${warnedMissingPricing.size} integration models; pi usage cost will be reported as zero`,
    );
  }

  const out = new Map<string, IntegrationProviderInfo>();
  for (const [provider, entry] of grouped) {
    const models: ProviderModelConfig[] = [];
    const modelAliases = new Map<string, string>();
    const chatGPTModelIds = new Set<string>();
    for (const candidate of entry.candidates) {
      const modelConfig = integrationModelConfig(candidate);
      models.push(modelConfig);
      modelAliases.set(modelConfig.id, candidate.nativeID);
      if (integrationModelNeedsChatGPTPayloadRewrite(candidate)) {
        chatGPTModelIds.add(modelConfig.id);
      }
    }
    const first = models[0];
    if (!first?.baseUrl) continue;
    const config: ProviderConfig = {
      name: integrationProviderDisplayName(entry.names),
      baseUrl: first.baseUrl,
      apiKey: "integration",
      models,
    };
    out.set(
      `exe-dev-${provider}`,
      integrationProviderInfo(config, {
        modelAliases: modelAliases.size > 0 ? modelAliases : undefined,
        chatGPTModelIds: chatGPTModelIds.size > 0 ? chatGPTModelIds : undefined,
      }),
    );
  }
  return out;
}

// sanitizeCompat copies only fields whose values pi-ai understands. Unknown
// values would misconfigure the model silently; dropping them lets pi-ai fall
// back to its URL-based auto-detection. Returns undefined if nothing is set.
function sanitizeCompat(c: CatalogCompat | undefined, providerId: string, modelId: string): CompatBag | undefined {
  if (!c) return undefined;
  const out: CompatBag = {};
  if (typeof c.supportsDeveloperRole === "boolean") out.supportsDeveloperRole = c.supportsDeveloperRole;
  if (typeof c.supportsReasoningEffort === "boolean") out.supportsReasoningEffort = c.supportsReasoningEffort;
  if (c.maxTokensField) {
    if (KNOWN_MAX_TOKENS_FIELDS.has(c.maxTokensField)) {
      out.maxTokensField = c.maxTokensField as CompatBag["maxTokensField"];
    } else {
      console.warn(`[pi-exe-dev] dropping unknown maxTokensField "${c.maxTokensField}" on ${providerId}/${modelId}`);
    }
  }
  if (c.thinkingFormat) {
    if (KNOWN_THINKING_FORMATS.has(c.thinkingFormat)) {
      out.thinkingFormat = c.thinkingFormat as CompatBag["thinkingFormat"];
    } else {
      console.warn(`[pi-exe-dev] dropping unknown thinkingFormat "${c.thinkingFormat}" on ${providerId}/${modelId}`);
    }
  }
  if (c.cacheControlFormat) {
    if (KNOWN_CACHE_CONTROL_FORMATS.has(c.cacheControlFormat)) {
      out.cacheControlFormat = c.cacheControlFormat as CompatBag["cacheControlFormat"];
    } else {
      console.warn(`[pi-exe-dev] dropping unknown cacheControlFormat "${c.cacheControlFormat}" on ${providerId}/${modelId}`);
    }
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

function managedBaseUrls(config: ProviderConfig): ReadonlySet<string> {
  const out = new Set<string>();
  if (config.baseUrl) out.add(config.baseUrl);
  for (const model of config.models ?? []) {
    if (model.baseUrl) out.add(model.baseUrl);
  }
  return out;
}

function integrationProviderInfo(
  config: ProviderConfig,
  rewrite?: Omit<IntegrationProviderPayloadRewrite, "selectedModelID">,
): IntegrationProviderInfo {
  return {
    config,
    modelAliases: rewrite?.modelAliases,
    chatGPTModelIds: rewrite?.chatGPTModelIds,
    baseUrls: managedBaseUrls(config),
  };
}
