import assert from "node:assert/strict";
import test from "node:test";
import { nativeModelIDForGeneratedModel, rewriteIntegrationProviderPayload } from "./request_rewrite.ts";

test("rewrites only aliases generated by the extension", () => {
  const aliases = new Map([["gpt-5.5@Some_Integration", "gpt-5.5"]]);

  assert.deepEqual(
    rewriteIntegrationProviderPayload(
      { model: "gpt-5.5@Some_Integration", input: "hi", max_output_tokens: 12 },
      { modelAliases: aliases },
    ),
    { model: "gpt-5.5", input: "hi", max_output_tokens: 12 },
  );
  assert.equal(nativeModelIDForGeneratedModel("claude-3-5-sonnet@20240620", aliases), undefined);
  assert.equal(
    rewriteIntegrationProviderPayload({ model: "claude-3-5-sonnet@20240620", input: "hi" }, { modelAliases: aliases }),
    undefined,
  );
});

test("applies ChatGPT rewrite only for marked generated model ids", () => {
  const aliases = new Map([["gpt-5.5@chatgpt-sub", "gpt-5.5"]]);
  const chatGPTModelIds = new Set(["gpt-5.5@chatgpt-sub"]);

  assert.deepEqual(
    rewriteIntegrationProviderPayload(
      {
        model: "gpt-5.5@chatgpt-sub",
        instructions: "base",
        input: [
          { role: "developer", content: "developer text" },
          { role: "system", content: [{ type: "input_text", text: "system text" }] },
          { role: "user", content: "Say ok." },
        ],
        max_output_tokens: 100,
        max_tokens: 100,
        max_completion_tokens: 100,
      },
      { modelAliases: aliases, chatGPTModelIds },
    ),
    {
      model: "gpt-5.5",
      instructions: "base\n\ndeveloper text\n\nsystem text",
      input: [{ role: "user", content: "Say ok." }],
      max_output_tokens: 100,
      max_tokens: 100,
      max_completion_tokens: 100,
      store: false,
      text: { verbosity: "low" },
      include: ["reasoning.encrypted_content"],
      tool_choice: "auto",
      parallel_tool_calls: true,
    },
  );

  assert.deepEqual(
    rewriteIntegrationProviderPayload(
      { model: "gpt-5.5@managed-sub", input: "hi", max_output_tokens: 100 },
      { modelAliases: new Map([["gpt-5.5@managed-sub", "gpt-5.5"]]), chatGPTModelIds },
    ),
    { model: "gpt-5.5", input: "hi", max_output_tokens: 100 },
  );
});

test("uses selected model id when pi omits model from the outgoing payload", () => {
  assert.deepEqual(
    rewriteIntegrationProviderPayload(
      {
        input: [
          { role: "developer", content: "developer text" },
          { role: "system", content: "system text" },
          { role: "user", content: "hi" },
        ],
        max_output_tokens: 100,
      },
      { selectedModelID: "gpt-5.5", chatGPTModelIds: new Set(["gpt-5.5"]) },
    ),
    {
      input: [{ role: "user", content: "hi" }],
      instructions: "developer text\n\nsystem text",
      max_output_tokens: 100,
      store: false,
      text: { verbosity: "low" },
      include: ["reasoning.encrypted_content"],
      tool_choice: "auto",
      parallel_tool_calls: true,
    },
  );
});

test("preserves explicit Codex payload options for ChatGPT models", () => {
  assert.deepEqual(
    rewriteIntegrationProviderPayload(
      {
        model: "gpt-5.5@chatgpt-sub",
        input: "hi",
        text: { verbosity: "high" },
        include: ["file_search_call.results"],
        tool_choice: "required",
        parallel_tool_calls: false,
      },
      {
        modelAliases: new Map([["gpt-5.5@chatgpt-sub", "gpt-5.5"]]),
        chatGPTModelIds: new Set(["gpt-5.5@chatgpt-sub"]),
      },
    ),
    {
      model: "gpt-5.5",
      input: "hi",
      text: { verbosity: "high" },
      include: ["file_search_call.results", "reasoning.encrypted_content"],
      tool_choice: "required",
      parallel_tool_calls: false,
      store: false,
    },
  );
});
